#!/bin/bash
protected_branch='master'  
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
if [ "${current_branch}" = "${protected_branch}" ]; then
    echo "Direct commits to the branch 'master' are not allowed. Use '--no-verify' to bypass the pre-commit and commit-msg hooks"
    exit 1
fi
